"""add_project_and_team_mapping_tables

Revision ID: b24c2980faad
Revises: 001
Create Date: 2025-12-16 19:22:24.313873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b24c2980faad'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_identities',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('committer_email', sa.String(length=255), nullable=False),
    sa.Column('committer_name', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'committer_email', name='uq_github_identity_email')
    )
    op.create_index(op.f('ix_github_identities_tenant_id'), 'github_identities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_github_identities_user_id'), 'github_identities', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('discord_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_thread_name', sa.String(length=255), nullable=True),
    sa.Column('discord_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_launch_date', sa.Date(), nullable=True),
    sa.Column('actual_launch_date', sa.Date(), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kpi_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('launch_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_ai_analysis', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_discord_thread_id'), 'projects', ['discord_thread_id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('tenant_project_configs',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('task_channel_name', sa.String(length=255), nullable=True),
    sa.Column('thread_name_pattern', sa.String(length=255), nullable=False),
    sa.Column('auto_create_projects', sa.Boolean(), nullable=False),
    sa.Column('report_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_kpis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_project_configs_tenant_id'), 'tenant_project_configs', ['tenant_id'], unique=True)
    op.create_table('project_github_links',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('github_connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('branch_filter', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['github_connection_id'], ['github_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'github_connection_id', name='uq_project_github')
    )
    op.create_index(op.f('ix_project_github_links_github_connection_id'), 'project_github_links', ['github_connection_id'], unique=False)
    op.create_index(op.f('ix_project_github_links_project_id'), 'project_github_links', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_github_links_project_id'), table_name='project_github_links')
    op.drop_index(op.f('ix_project_github_links_github_connection_id'), table_name='project_github_links')
    op.drop_table('project_github_links')
    op.drop_index(op.f('ix_tenant_project_configs_tenant_id'), table_name='tenant_project_configs')
    op.drop_table('tenant_project_configs')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_discord_thread_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_github_identities_user_id'), table_name='github_identities')
    op.drop_index(op.f('ix_github_identities_tenant_id'), table_name='github_identities')
    op.drop_table('github_identities')
    # ### end Alembic commands ###
